name: InactiveRegions
version: DEVELOPMENTAL_SNAPSHOT_Build-x307c_09-08-2015
description: Utility Plugin
depend: [Vault]
author: Fahlur
main: me.Fahlur.InactiveRegions.main

commands:
  inactiveregions:
      description: Main Command
      aliases: [ia]
      usage: /<command>
Permissions:
  ia.List:
    description: Lists all inactive or invalid Regions
  ia.Whitelist:
    description: Use whitelisting tool
    
