name: Inactive Regions
main: me.Fahlur.InactiveRegions.main
version: 1.1.0
author: Fahlur
description: Inactive Regions Check
api-version: 1.12
depend: []

commands:
  ia:
      description: Plugin Main Command
      usage: /<command>
