name: InactiveRegions
version: SNAPSHOT_Build-x307a_08-05-2015
description: Utility Plugin
depend: [Vault]
author: Fahlur
main: me.Fahlur.InactiveRegions.main

commands:
  oldregions:
      description: Displays entire list of inactive regions
      aliases: [or]
      usage: /<command>
  inactiveregions:
      description: Displays plugin version information
      aliases: [ia]
      usage: /<command>
Permissions:
  InactiveRegionsList:
    description: Allows use of oldregions command
